#!/usr/bin/env python

import os
import sys


in_file = open(sys.argv[1], 'r')

for line in in_file:
  # if line.isspace():
    # print

  if (not line.startswith("M") ):
    print line[:-1]

  else:
    if (line.startswith("M  END") ):
      print line[:-1]
